site_name: "HORTUS"
theme:
  name: "material"
  palette:
    primary: green
    accent: light green
  features:
    - navigation.instant
    #- navigation.tabs

nav:
    - Home: index.md
    - Design Stages: design-stages.md
    - Blog:
        #- "3 R's": rrr.md
        - "Reactors, Robots & Rockets": rrr.md
        - Zero Waste: zerowaste.md
        - Vegan: vegan.md

plugins:
  - mkdocstrings

markdown_extensions:
  - toc:
      permalink: True
