site_name: "VITA"
theme:
  name: "material"
  palette:
    primary: green
    accent: light green
  features:
    - navigation.instant
    - navigation.tabs

nav:
    - Overview: overview.md
    - Zero Waste: zerowaste.md
    - Vegan: vegan.md

plugins:
  - mkdocstrings

markdown_extensions:
  - toc:
      permalink: True
