site_name: "HORTUS"
docs_dir: "site"
site_dir: "docs"
theme:
  name: "material"
  font: false
  palette:
    primary: green
    accent: light green
  features:
    - navigation.instant
    #- navigation.tabs

nav:
    - Home: index.md
    - Plant Information: plant-info.md
    - Design Stages: design-stages.md
    - Blog:
        #- "3 R's": rrr.md
        - "Robots, Reactors & Rockets": rrr.md
        - "Food, Forests & Freedom": fff.md
        - Zero Waste: zerowaste.md
        - Vegan: vegan.md

plugins:
  - mkdocstrings
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

markdown_extensions:
  - toc:
      permalink: True
